# Host Authentication Information
ansible_user: ubuntu
ansible_become_user: root
#ansible_ssh_pass: "[PUT_LOGIN_PASSWORD_HERE]"
ansible_ssh_private_key_file: /k8s-deploy/ssh-privkey/id_rsa
# Python location in Ubuntu 16.04 cloud image
# You need to change the path if python in different location
ansible_python_interpreter: /usr/bin/python3.5

# Valid bootstrap options (required): ubuntu, coreos, centos, none
bootstrap_os: ubuntu

#Directory where etcd data stored
etcd_data_dir: /var/lib/etcd

# Directory where the binaries will be installed
bin_dir: /usr/local/bin