---

- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - include_tasks: "{{playbook_dir}}/node-preconfig.debian-family.yml"
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include_tasks: "{{playbook_dir}}/node-preconfig.redhat-family.yml"
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'