---

- hosts: kube-master
  gather_facts: yes
  become: yes
  tasks:
  - name: "Get home directory of user {{ ansible_ssh_user }}"
    shell: "grep '{{ ansible_ssh_user }}' /etc/passwd | cut -d':' -f6"
    register: USER_HOME_DIR

  - name: "Create kubeconfig directory"
    block:
    - name: "Create kubeconfig directory | /root/.kube"
      file:
        path: "/root/.kube"
        state: directory
        mode: '0755'
        owner: "root"
        group: "root"
    - name: "Create kubeconfig directory | {{ USER_HOME_DIR.stdout }}/.kube"
      file:
        path: "{{ USER_HOME_DIR.stdout }}/.kube"
        state: directory
        mode: '0755'
        owner: "{{ ansible_ssh_user }}"

  - name: "Copy kubeconfig"
    block:
    - name: "Copy kubeconfig (for root)"
      shell: "cp /etc/kubernetes/admin.conf /root/.kube/config"

    - name: "Copy kubeconfig (for root) | change file permission"
      file:
        path: "/root/.kube/config"
        owner: "root"

    - name: "Copy kubeconfig (for {{ ansible_ssh_user }})"
      shell: "cp /etc/kubernetes/admin.conf {{ USER_HOME_DIR.stdout }}/.kube/config"

    - name: "Copy kubeconfig (for {{ ansible_ssh_user }}) | change file permission"
      file:
        path: "{{ USER_HOME_DIR.stdout }}/.kube/config"
        owner: "{{ ansible_ssh_user }}"
